### ISSUE TITLE
Camera jumps when bumping into a wall

### ISSUE THREAD

**Issue by pelya** [retux-game/retux#1]
Get some acceleration and run into the wall. The camera jerks back and it's uncomfortable for eyes.

**Comment by onpon4** [comment]
That's a good point, yes. I'll need to think of a way to make that better.

🕷️

**Comment by onpon4** [comment]
We fixed this by adding a horizontal camera speed limit while horizontally stopped. Should be much better.

We'll have to incorporate this fix into Hexoshi as well.
