### ISSUE TITLE
(Bug) Retux.py Doesn't start up .

### ISSUE THREAD

**Issue by RandomPenguin1778** [retux-game/retux#5]
Hello Retux Team ! ,
I downloaded the retux source code and extracted it . then i ran 'Retux.py' But nothing happens . please fix this issue as soon as possible

**Comment by onpon4** [comment]
Did you install the dependencies?

As stated in the readme, you need Python 3.6 or later (https://www.python.org), and you need all of the dependencies listed by requirements.txt. Under Windows, after Python is installed, you should be able to install them all from Command Prompt with the following command:

```
py -m pip install --upgrade pygame uniseg sge xsge_gui xsge_lighting xsge_path xsge_physics xsge_tiled
```

If you've ensured all dependencies are installed, please run get_errors.py and see if any errors have been logged, and if any have been, please attach the log here so I can review it.

🕵️

**Comment by deonsebastiandk** [comment]
I tried the command in cmd but it didn't respond . i tried again in the python command line but it isn't a valid syntax .

**Comment by onpon4** [comment]
What exactly do you mean when you say it "didn't respond"? Did you get an error message?

🕵️

**Comment by deonsebastiandk** [comment]
No but the command prompt just stayed idle like nothing was happening

**Comment by deonsebastiandk** [comment]
Is there any issues with my python installation?

**Comment by onpon4** [comment]
I can't know whether or not there's a problem with your Python installation, but if it's installed properly, typing `py` by itself into Command Prompt will give you a prompt where you can type Python code (which will also tell you what version of Python is running); it should look something like this:

```
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

You should also be able to run `py -m pip --help` to print a list of command line options for pip.

Do these descriptions match the output you get when you try `py` and `py -m pip --version`?

🕵️

**Comment by RandomPenguin1778** [comment]
Yes .

**Comment by onpon4** [comment]
Ok. Well, my best guess is that you just didn't wait long enough for pip to do its work, maybe. Can you try the command I suggested above and ensure you give it a few minutes?

🕵️

**Comment by RandomPenguin1778** [comment]
Ok ! thanks for the help !
