### ISSUE TITLE
Windows Defender flags 1.5 as a Trojan

### ISSUE THREAD

**Issue by enderandrew** [retux-game/retux#6]
So either the release has malicious code (which I assume is unlikely) or Defender is flagging this as a false positive. 

I believe you can report false positives to Microsoft so they won't flag them in the future.

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide
![retux-trojan](https://user-images.githubusercontent.com/904137/130658677-6cc41eed-2f86-4972-99a2-74043e27ee0d.jpg)

**Comment by onpon4** [comment]
I've sent it to Microsoft, so hopefully they fix it. Yes, it's a false positive.

🕵️

**Comment by CrisisModel** [comment]
This issue should probably be closed. With the latest version, 1.6.1, VirusTotal does not flag anything in the win64 zip as malicious. Check [here](https://www.virustotal.com/gui/url/62f47c0d834e80330dd1f2a2364919b75b7647b97af76e7fca4f3d11d85de8c2/detection) for the result of that. Running the retux.exe file itself through VirusTotal [shows](https://www.virustotal.com/gui/file/4b11ee3c549dd0ce71c2cb81ec54aa007c7f4c01ca4162f33358bbc8644932df/detection) that Microsoft no longer considers it to have any sort of threat, though it does get flagged by some obscure antivirus vendors (minus Google, which theirs is only for Chrome's download scanning) as having a generic "threat," which is obviously false positives.
